# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sendsave_pb2 as sendsave__pb2


class SendSaveServiceStub(object):
    """Missing associated documentation comment in .proto file."""
  
    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.unary_unary(
                '/SendSaveService/send',
                request_serializer=sendsave__pb2.Send.SerializeToString,
                response_deserializer=sendsave__pb2.save.FromString,
                )


class SendSaveServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendSaveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=sendsave__pb2.Send.FromString,
                    response_serializer=sendsave__pb2.save.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SendSaveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SendSaveService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SendSaveService/send',
            sendsave__pb2.Send.SerializeToString,
            sendsave__pb2.save.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
