# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sendsave.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sendsave.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esendsave.proto\"\x15\n\x04Send\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x15\n\x04save\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32)\n\x0fSendSaveService\x12\x16\n\x04send\x12\x05.Send\x1a\x05.save\"\x00\x62\x06proto3'
)




_SEND = _descriptor.Descriptor(
  name='Send',
  full_name='Send',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='Send.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=39,
)


_SAVE = _descriptor.Descriptor(
  name='save',
  full_name='save',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='save.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['Send'] = _SEND
DESCRIPTOR.message_types_by_name['save'] = _SAVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Send = _reflection.GeneratedProtocolMessageType('Send', (_message.Message,), {
  'DESCRIPTOR' : _SEND,
  '__module__' : 'sendsave_pb2'
  # @@protoc_insertion_point(class_scope:Send)
  })
_sym_db.RegisterMessage(Send)

save = _reflection.GeneratedProtocolMessageType('save', (_message.Message,), {
  'DESCRIPTOR' : _SAVE,
  '__module__' : 'sendsave_pb2'
  # @@protoc_insertion_point(class_scope:save)
  })
_sym_db.RegisterMessage(save)



_SENDSAVESERVICE = _descriptor.ServiceDescriptor(
  name='SendSaveService',
  full_name='SendSaveService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=64,
  serialized_end=105,
  methods=[
  _descriptor.MethodDescriptor(
    name='send',
    full_name='SendSaveService.send',
    index=0,
    containing_service=None,
    input_type=_SEND,
    output_type=_SAVE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDSAVESERVICE)

DESCRIPTOR.services_by_name['SendSaveService'] = _SENDSAVESERVICE

# @@protoc_insertion_point(module_scope)
